project_id = "cxiceumycfzofrrbwgwr"

[functions.magic-invite]
verify_jwt = false

[functions.accept-invitation]
verify_jwt = false

[functions.send-invitation]
verify_jwt = false

[functions.send-test-email]
verify_jwt = false

[functions.reset-database]
verify_jwt = true

[functions.create-admin]
verify_jwt = false

[functions.admin-create-household]
verify_jwt = false

[functions.admin-invite-parent]
verify_jwt = false

[functions.admin-reset-password]
verify_jwt = false

[functions.admin-trigger-forgot-password]
verify_jwt = false

[functions.admin-delete-household]
verify_jwt = false

[functions.admin-list-households]
verify_jwt = false

[functions.admin-resend-invitation]
verify_jwt = false

[functions.calendar-feed]
verify_jwt = false

[functions.admin-approve-access-request]
verify_jwt = false

[functions.admin-reject-access-request]
verify_jwt = false

[functions.notify-admin-access-request]
verify_jwt = false
